// Autogenerated from Pigeon (v26.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.luix.connect_kit.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object ConnectKitMessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * TODO: Add documentation
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AccessStatusMessage (
  val dataAccess: Map<String, Any>? = null,
  val historyAccess: String? = null,
  val backgroundAccess: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AccessStatusMessage {
      val dataAccess = pigeonVar_list[0] as Map<String, Any>?
      val historyAccess = pigeonVar_list[1] as String?
      val backgroundAccess = pigeonVar_list[2] as String?
      return AccessStatusMessage(dataAccess, historyAccess, backgroundAccess)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      dataAccess,
      historyAccess,
      backgroundAccess,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is AccessStatusMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return ConnectKitMessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Platform message representing the result of a record write operation.
 *
 * This class is generated by Pigeon and used to pass data from the platform
 * (Kotlin/Swift) to Dart.
 *
 * **Fields:**
 * - [outcome]: One of `"completeSuccess"`, `"partialSuccess"`, or `"failure"`.
 * - [persistedRecordIds]: List of record IDs that were successfully persisted.
 *   (Available on Android; always `null` on iOS.)
 * - [validationFailures]: Optional list of validation/decoding failures.
 *   Each item is a map containing:
 *   - `"indexPath"`: `List<int>` identifying the failed record location
 *     (e.g., `[0]` for the first top-level record, `[1, 2]` for the third
 *     record within duringSession of the second top-level record).
 *   - `"message"`: Human-readable error description (e.g., `"Missing field 'date'"`).
 *   - `"type"`: Optional error category (e.g., `"ValidationError"`).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class WriteResultMessage (
  val outcome: String,
  val persistedRecordIds: List<String>? = null,
  val validationFailures: List<Map<String, Any>>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WriteResultMessage {
      val outcome = pigeonVar_list[0] as String
      val persistedRecordIds = pigeonVar_list[1] as List<String>?
      val validationFailures = pigeonVar_list[2] as List<Map<String, Any>>?
      return WriteResultMessage(outcome, persistedRecordIds, validationFailures)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      outcome,
      persistedRecordIds,
      validationFailures,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is WriteResultMessage) {
      return false
    }
    if (this === other) {
      return true
    }
    return ConnectKitMessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class ConnectKitMessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AccessStatusMessage.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WriteResultMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AccessStatusMessage -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is WriteResultMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ConnectKitHostApi {
  fun getPlatformVersion(callback: (Result<String>) -> Unit)
  fun isSdkAvailable(callback: (Result<String>) -> Unit)
  fun requestPermissions(readTypes: List<String>?, writeTypes: List<String>?, forHistory: Boolean?, forBackground: Boolean?, callback: (Result<Boolean>) -> Unit)
  fun checkPermissions(forData: Map<String, List<String>>?, forHistory: Boolean?, forBackground: Boolean?, callback: (Result<AccessStatusMessage>) -> Unit)
  fun revokePermissions(callback: (Result<Boolean>) -> Unit)
  fun openHealthSettings(callback: (Result<Boolean>) -> Unit)
  fun writeRecords(records: List<Map<String, Any?>>, callback: (Result<WriteResultMessage>) -> Unit)

  companion object {
    /** The codec used by ConnectKitHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      ConnectKitMessagesPigeonCodec()
    }
    /** Sets up an instance of `ConnectKitHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ConnectKitHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.connect_kit.ConnectKitHostApi.getPlatformVersion$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getPlatformVersion{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ConnectKitMessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ConnectKitMessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.connect_kit.ConnectKitHostApi.isSdkAvailable$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isSdkAvailable{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ConnectKitMessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ConnectKitMessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.connect_kit.ConnectKitHostApi.requestPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val readTypesArg = args[0] as List<String>?
            val writeTypesArg = args[1] as List<String>?
            val forHistoryArg = args[2] as Boolean?
            val forBackgroundArg = args[3] as Boolean?
            api.requestPermissions(readTypesArg, writeTypesArg, forHistoryArg, forBackgroundArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ConnectKitMessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ConnectKitMessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.connect_kit.ConnectKitHostApi.checkPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val forDataArg = args[0] as Map<String, List<String>>?
            val forHistoryArg = args[1] as Boolean?
            val forBackgroundArg = args[2] as Boolean?
            api.checkPermissions(forDataArg, forHistoryArg, forBackgroundArg) { result: Result<AccessStatusMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ConnectKitMessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ConnectKitMessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.connect_kit.ConnectKitHostApi.revokePermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.revokePermissions{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ConnectKitMessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ConnectKitMessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.connect_kit.ConnectKitHostApi.openHealthSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.openHealthSettings{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ConnectKitMessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ConnectKitMessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.connect_kit.ConnectKitHostApi.writeRecords$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recordsArg = args[0] as List<Map<String, Any?>>
            api.writeRecords(recordsArg) { result: Result<WriteResultMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ConnectKitMessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ConnectKitMessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
