import 'package:pigeon/pigeon.dart';

// The configuration for the Pigeon tool, specifying all input and output files,
// as well as platform class names for the generated code.
//
// INFO: To regenerate files, run:
// flutter pub run pigeon --input pigeon/messages.dart
@ConfigurePigeon(
  PigeonOptions(
    dartPackageName: 'connect_kit',
    dartOut: 'lib/src/pigeon/connect_kit_messages.g.dart',
    dartOptions: DartOptions(),
    dartTestOut: 'test/pigeon/connect_kit_test_api.g.dart',
    kotlinOut:
        'android/src/main/kotlin/dev/luix/connect_kit/pigeon/ConnectKitMessages.g.kt',
    kotlinOptions: KotlinOptions(
      package: 'dev.luix.connect_kit.pigeon',
      // errorClassName: 'ConnectKitError',
    ),
    swiftOut: 'ios/Classes/Pigeon/ConnectKitMessages.g.swift',
    swiftOptions: SwiftOptions(
        // errorClassName: 'ConnectKitError',
        ),

    // INFO: Leaving the following commented our to test, since some references attest
    //       that is needed, while other says it is not
    //
    // // REQUIRED: Objective-C output paths for Swift/Flutter bridging
    // objcHeaderOut: 'ios/Classes/Pigeon/connect_kit_messages.h',
    // objcSourceOut: 'ios/Classes/Pigeon/connect_kit_messages.m',
    // objcOptions: ObjcOptions(
    //   prefix: 'ConnectKit', // Use a clear prefix to avoid naming collisions
    // ),

    // copyrightHeader: 'Copyright(c) 2025-present ConnectKit. All rights reserved.',
  ),
)

/// TODO: Add documentation
class AccessStatusMessage {
  Map<String, Object>? dataAccess; // INFO: inner-maps not supported
  String? historyAccess;
  String? backgroundAccess;

  AccessStatusMessage({
    this.dataAccess,
    this.historyAccess,
    this.backgroundAccess,
  });
}

/// Platform message representing the result of a record write operation.
///
/// This class is generated by Pigeon and used to pass data from the platform
/// (Kotlin/Swift) to Dart.
///
/// **Fields:**
/// - [outcome]: One of `"completeSuccess"`, `"partialSuccess"`, or `"failure"`.
/// - [persistedRecordIds]: List of record IDs that were successfully persisted.
///   (Available on Android; always `null` on iOS.)
/// - [validationFailures]: Optional list of validation/decoding failures.
///   Each item is a map containing:
///   - `"indexPath"`: `List<int>` identifying the failed record location
///     (e.g., `[0]` for the first top-level record, `[1, 2]` for the third
///     record within duringSession of the second top-level record).
///   - `"message"`: Human-readable error description (e.g., `"Missing field 'date'"`).
///   - `"type"`: Optional error category (e.g., `"ValidationError"`).
class WriteResultMessage {
  String outcome;
  List<String>? persistedRecordIds;
  List<Map<String, Object>>? validationFailures;

  WriteResultMessage({
    required this.outcome,
    this.persistedRecordIds,
    this.validationFailures,
  });
}

@HostApi()
abstract class ConnectKitHostApi {
  @async
  String getPlatformVersion();

  @async
  String isSdkAvailable();

  @async
  bool requestPermissions(
    List<String>? readTypes,
    List<String>? writeTypes,
    bool? forHistory,
    bool? forBackground,
  );

  @async
  AccessStatusMessage checkPermissions(
    Map<String, List<String>>? forData,
    bool? forHistory,
    bool? forBackground,
  );

  @async
  bool revokePermissions();

  @async
  bool openHealthSettings();

  @async
  WriteResultMessage writeRecords(List<Map<String, Object?>> records);
}
