// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by: dart run tool/generate_ck_type.dart
// Generated at: 2025-11-07T15:20:51.629912

part of 'ck_type.dart';

class _$CKTypeRegistry {
  static final Map<String, CKType> _registry = {
    'activeEnergy': CKType.activeEnergy,
    'activityIntensity': CKType.activityIntensity,
    'basalBodyTemperature': CKType.basalBodyTemperature,
    'biologicalSex': CKType.biologicalSex,
    'bloodGlucose': CKType.bloodGlucose,
    'bloodPressure': CKType.bloodPressure,
    'bloodPressure.diastolic': CKType.bloodPressure.diastolic,
    'bloodPressure.systolic': CKType.bloodPressure.systolic,
    'bloodType': CKType.bloodType,
    'bodyFat': CKType.bodyFat,
    'bodyMassIndex': CKType.bodyMassIndex,
    'bodyTemperature': CKType.bodyTemperature,
    'bodyWaterMass': CKType.bodyWaterMass,
    'boneMass': CKType.boneMass,
    'cervicalMucus': CKType.cervicalMucus,
    'contraceptive': CKType.contraceptive,
    'cyclingPedalingCadence': CKType.cyclingPedalingCadence,
    'cyclingPower': CKType.cyclingPower,
    'dateOfBirth': CKType.dateOfBirth,
    'distance': CKType.distance,
    'distanceCycling': CKType.distanceCycling,
    'distanceDownhillSnowSports': CKType.distanceDownhillSnowSports,
    'distanceSwimming': CKType.distanceSwimming,
    'distanceWheelchair': CKType.distanceWheelchair,
    'elevation': CKType.elevation,
    'environmentalAudioExposure': CKType.environmentalAudioExposure,
    'fitzpatrickSkinType': CKType.fitzpatrickSkinType,
    'floorsClimbed': CKType.floorsClimbed,
    'headphoneAudioExposure': CKType.headphoneAudioExposure,
    'heartRate': CKType.heartRate,
    'heartRateVariability': CKType.heartRateVariability,
    'height': CKType.height,
    'intermenstrualBleeding': CKType.intermenstrualBleeding,
    'lactation': CKType.lactation,
    'leanBodyMass': CKType.leanBodyMass,
    'menstrualFlow': CKType.menstrualFlow,
    'menstruationPeriod': CKType.menstruationPeriod,
    'mindfulSession': CKType.mindfulSession,
    'numberOfAlcoholicBeverages': CKType.numberOfAlcoholicBeverages,
    'nutrition': CKType.nutrition,
    'nutrition.biotin': CKType.nutrition.biotin,
    'nutrition.caffeine': CKType.nutrition.caffeine,
    'nutrition.calcium': CKType.nutrition.calcium,
    'nutrition.carbs': CKType.nutrition.carbs,
    'nutrition.chloride': CKType.nutrition.chloride,
    'nutrition.cholesterol': CKType.nutrition.cholesterol,
    'nutrition.chromium': CKType.nutrition.chromium,
    'nutrition.copper': CKType.nutrition.copper,
    'nutrition.energy': CKType.nutrition.energy,
    'nutrition.fat': CKType.nutrition.fat,
    'nutrition.fiber': CKType.nutrition.fiber,
    'nutrition.folate': CKType.nutrition.folate,
    'nutrition.iodine': CKType.nutrition.iodine,
    'nutrition.iron': CKType.nutrition.iron,
    'nutrition.magnesium': CKType.nutrition.magnesium,
    'nutrition.manganese': CKType.nutrition.manganese,
    'nutrition.molybdenum': CKType.nutrition.molybdenum,
    'nutrition.monounsaturatedFat': CKType.nutrition.monounsaturatedFat,
    'nutrition.niacin': CKType.nutrition.niacin,
    'nutrition.pantothenicAcid': CKType.nutrition.pantothenicAcid,
    'nutrition.phosphorus': CKType.nutrition.phosphorus,
    'nutrition.polyunsaturatedFat': CKType.nutrition.polyunsaturatedFat,
    'nutrition.potassium': CKType.nutrition.potassium,
    'nutrition.protein': CKType.nutrition.protein,
    'nutrition.riboflavin': CKType.nutrition.riboflavin,
    'nutrition.saturatedFat': CKType.nutrition.saturatedFat,
    'nutrition.selenium': CKType.nutrition.selenium,
    'nutrition.sodium': CKType.nutrition.sodium,
    'nutrition.sugar': CKType.nutrition.sugar,
    'nutrition.thiamin': CKType.nutrition.thiamin,
    'nutrition.transFat': CKType.nutrition.transFat,
    'nutrition.unsaturatedFat': CKType.nutrition.unsaturatedFat,
    'nutrition.vitaminA': CKType.nutrition.vitaminA,
    'nutrition.vitaminB12': CKType.nutrition.vitaminB12,
    'nutrition.vitaminB6': CKType.nutrition.vitaminB6,
    'nutrition.vitaminC': CKType.nutrition.vitaminC,
    'nutrition.vitaminD': CKType.nutrition.vitaminD,
    'nutrition.vitaminE': CKType.nutrition.vitaminE,
    'nutrition.vitaminK': CKType.nutrition.vitaminK,
    'nutrition.zinc': CKType.nutrition.zinc,
    'ovulationTest': CKType.ovulationTest,
    'oxygenSaturation': CKType.oxygenSaturation,
    'peripheralPerfusionIndex': CKType.peripheralPerfusionIndex,
    'power': CKType.power,
    'pregnancy': CKType.pregnancy,
    'progesteroneTest': CKType.progesteroneTest,
    'pushCount': CKType.pushCount,
    'respiratoryRate': CKType.respiratoryRate,
    'restingEnergy': CKType.restingEnergy,
    'restingHeartRate': CKType.restingHeartRate,
    'runningPower': CKType.runningPower,
    'sexualActivity': CKType.sexualActivity,
    'sixMinuteWalkDistance': CKType.sixMinuteWalkDistance,
    'skinTemperature': CKType.skinTemperature,
    'sleepSession': CKType.sleepSession,
    'sleepSession.asleep': CKType.sleepSession.asleep,
    'sleepSession.awake': CKType.sleepSession.awake,
    'sleepSession.deep': CKType.sleepSession.deep,
    'sleepSession.inBed': CKType.sleepSession.inBed,
    'sleepSession.light': CKType.sleepSession.light,
    'sleepSession.outOfBed': CKType.sleepSession.outOfBed,
    'sleepSession.rem': CKType.sleepSession.rem,
    'speed': CKType.speed,
    'stairSpeed': CKType.stairSpeed,
    'steps': CKType.steps,
    'swimmingStrokeCount': CKType.swimmingStrokeCount,
    'timeInDaylight': CKType.timeInDaylight,
    'totalEnergy': CKType.totalEnergy,
    'uvExposure': CKType.uvExposure,
    'vo2Max': CKType.vo2Max,
    'walkingAsymmetry': CKType.walkingAsymmetry,
    'walkingDoubleSupportPercentage': CKType.walkingDoubleSupportPercentage,
    'walkingSpeed': CKType.walkingSpeed,
    'walkingStepLength': CKType.walkingStepLength,
    'waterIntake': CKType.waterIntake,
    'weight': CKType.weight,
    'wheelchairPushes': CKType.wheelchairPushes,
    'workout': CKType.workout,
    'workout.distance': CKType.workout.distance,
    'workout.energy': CKType.workout.energy,
    'workout.heartRate': CKType.workout.heartRate,
    'workout.power': CKType.workout.power,
    'workout.speed': CKType.workout.speed,
  };

  static CKType fromString(String inputString) {
    if (inputString.isEmpty) {
      throw ArgumentError('Type string cannot be empty');
    }

    final type = _registry[inputString];
    if (type == null) {
      throw ArgumentError(
        'Unknown health type: "$inputString". '
        'Valid types: ${_registry.keys.join(", ")}',
      );
    }

    return type;
  }

  static CKType? fromStringOrNull(String inputString) {
    return _registry[inputString];
  }

  static bool isValid(String inputString) {
    return _registry.containsKey(inputString);
  }

  static List<CKType> get allTypes {
    return _registry.values.toList();
  }

  static List<String> get allTypeNames {
    return _registry.keys.toList();
  }
}
