// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_ck_unit.dart
// Generated on 2025-11-07T15:20:51.952275

part of 'ck_unit.dart';

/// Base unit class.
/// Properties are defined via @ck-base-unit annotation.
abstract class CKUnit {
  final String symbol;

  const CKUnit(
    this.symbol
  );

  static const mass = _CKMassUnitNamespace();
  static const length = _CKLengthUnitNamespace();
  static const energy = _CKEnergyUnitNamespace();
  static const power = _CKPowerUnitNamespace();
  static const pressure = _CKPressureUnitNamespace();
  static const temperature = _CKTemperatureUnitNamespace();
  static const frequency = _CKFrequencyUnitNamespace();
  static const velocity = _CKVelocityUnitNamespace();
  static const volume = _CKVolumeUnitNamespace();
  static const scalar = _CKScalarUnitNamespace();
  static const bloodGlucose = _CKBloodGlucoseUnitNamespace();
}

/// CKMassUnit-specific unit class, inherits from CKUnit.
class CKMassUnit extends CKUnit {
  const CKMassUnit(super.symbol);

  static const kilogram = CKMassUnit('kg');
  static const gram = CKMassUnit('g');
  static const milligram = CKMassUnit('mg');
  static const pound = CKMassUnit('lb');
  static const ounces = CKMassUnit('oz');
}

/// CKLengthUnit-specific unit class, inherits from CKUnit.
class CKLengthUnit extends CKUnit {
  const CKLengthUnit(super.symbol);

  static const kilometer = CKLengthUnit('km');
  static const meter = CKLengthUnit('m');
  static const mile = CKLengthUnit('mi');
  static const foot = CKLengthUnit('ft');
  static const inch = CKLengthUnit('in');
}

/// CKEnergyUnit-specific unit class, inherits from CKUnit.
class CKEnergyUnit extends CKUnit {
  const CKEnergyUnit(super.symbol);

  static const kilocalorie = CKEnergyUnit('kcal');
  static const calorie = CKEnergyUnit('cal');
  static const kilojoule = CKEnergyUnit('kJ');
  static const joule = CKEnergyUnit('J');
}

/// CKPowerUnit-specific unit class, inherits from CKUnit.
class CKPowerUnit extends CKUnit {
  const CKPowerUnit(super.symbol);

  static const watt = CKPowerUnit('W');
  static const kilocaloriesPerDay = CKPowerUnit('kcal/day');
}

/// CKPressureUnit-specific unit class, inherits from CKUnit.
class CKPressureUnit extends CKUnit {
  const CKPressureUnit(super.symbol);

  static const millimetersOfMercury = CKPressureUnit('mmHg');
}

/// CKTemperatureUnit-specific unit class, inherits from CKUnit.
class CKTemperatureUnit extends CKUnit {
  const CKTemperatureUnit(super.symbol);

  static const celsius = CKTemperatureUnit('C');
  static const fahrenheit = CKTemperatureUnit('F');
}

/// CKFrequencyUnit-specific unit class, inherits from CKUnit.
class CKFrequencyUnit extends CKUnit {
  const CKFrequencyUnit(super.symbol);

  static const hertz = CKFrequencyUnit('Hz');
}

/// CKVelocityUnit-specific unit class, inherits from CKUnit.
class CKVelocityUnit extends CKUnit {
  const CKVelocityUnit(super.symbol);

  static const metersPerSecond = CKVelocityUnit('m/s');
  static const kilometersPerHour = CKVelocityUnit('kph');
  static const milesPerHour = CKVelocityUnit('mph');
}

/// CKVolumeUnit-specific unit class, inherits from CKUnit.
class CKVolumeUnit extends CKUnit {
  const CKVolumeUnit(super.symbol);

  static const liter = CKVolumeUnit('L');
  static const milliliter = CKVolumeUnit('mL');
  static const fluidOunceUS = CKVolumeUnit('fl. oz');
}

/// CKScalarUnit-specific unit class, inherits from CKUnit.
class CKScalarUnit extends CKUnit {
  const CKScalarUnit(super.symbol);

  static const count = CKScalarUnit('count');
  static const percent = CKScalarUnit('%');
}

/// CKBloodGlucoseUnit-specific unit class, inherits from CKUnit.
class CKBloodGlucoseUnit extends CKUnit {
  const CKBloodGlucoseUnit(super.symbol);

  static const millimolesPerLiter = CKBloodGlucoseUnit('mmol/L');
  static const milligramsPerDeciliter = CKBloodGlucoseUnit('mg/dL');
}

/// Namespace class enabling CKUnit.mass.unitName syntax.
class _CKMassUnitNamespace {
  const _CKMassUnitNamespace();

  CKMassUnit get kilogram => CKMassUnit.kilogram;
  CKMassUnit get gram => CKMassUnit.gram;
  CKMassUnit get milligram => CKMassUnit.milligram;
  CKMassUnit get pound => CKMassUnit.pound;
  CKMassUnit get ounces => CKMassUnit.ounces;
}

/// Namespace class enabling CKUnit.length.unitName syntax.
class _CKLengthUnitNamespace {
  const _CKLengthUnitNamespace();

  CKLengthUnit get kilometer => CKLengthUnit.kilometer;
  CKLengthUnit get meter => CKLengthUnit.meter;
  CKLengthUnit get mile => CKLengthUnit.mile;
  CKLengthUnit get foot => CKLengthUnit.foot;
  CKLengthUnit get inch => CKLengthUnit.inch;
}

/// Namespace class enabling CKUnit.energy.unitName syntax.
class _CKEnergyUnitNamespace {
  const _CKEnergyUnitNamespace();

  CKEnergyUnit get kilocalorie => CKEnergyUnit.kilocalorie;
  CKEnergyUnit get calorie => CKEnergyUnit.calorie;
  CKEnergyUnit get kilojoule => CKEnergyUnit.kilojoule;
  CKEnergyUnit get joule => CKEnergyUnit.joule;
}

/// Namespace class enabling CKUnit.power.unitName syntax.
class _CKPowerUnitNamespace {
  const _CKPowerUnitNamespace();

  CKPowerUnit get watt => CKPowerUnit.watt;
  CKPowerUnit get kilocaloriesPerDay => CKPowerUnit.kilocaloriesPerDay;
}

/// Namespace class enabling CKUnit.pressure.unitName syntax.
class _CKPressureUnitNamespace {
  const _CKPressureUnitNamespace();

  CKPressureUnit get millimetersOfMercury => CKPressureUnit.millimetersOfMercury;
}

/// Namespace class enabling CKUnit.temperature.unitName syntax.
class _CKTemperatureUnitNamespace {
  const _CKTemperatureUnitNamespace();

  CKTemperatureUnit get celsius => CKTemperatureUnit.celsius;
  CKTemperatureUnit get fahrenheit => CKTemperatureUnit.fahrenheit;
}

/// Namespace class enabling CKUnit.frequency.unitName syntax.
class _CKFrequencyUnitNamespace {
  const _CKFrequencyUnitNamespace();

  CKFrequencyUnit get hertz => CKFrequencyUnit.hertz;
}

/// Namespace class enabling CKUnit.velocity.unitName syntax.
class _CKVelocityUnitNamespace {
  const _CKVelocityUnitNamespace();

  CKVelocityUnit get metersPerSecond => CKVelocityUnit.metersPerSecond;
  CKVelocityUnit get kilometersPerHour => CKVelocityUnit.kilometersPerHour;
  CKVelocityUnit get milesPerHour => CKVelocityUnit.milesPerHour;
}

/// Namespace class enabling CKUnit.volume.unitName syntax.
class _CKVolumeUnitNamespace {
  const _CKVolumeUnitNamespace();

  CKVolumeUnit get liter => CKVolumeUnit.liter;
  CKVolumeUnit get milliliter => CKVolumeUnit.milliliter;
  CKVolumeUnit get fluidOunceUS => CKVolumeUnit.fluidOunceUS;
}

/// Namespace class enabling CKUnit.scalar.unitName syntax.
class _CKScalarUnitNamespace {
  const _CKScalarUnitNamespace();

  CKScalarUnit get count => CKScalarUnit.count;
  CKScalarUnit get percent => CKScalarUnit.percent;
}

/// Namespace class enabling CKUnit.bloodGlucose.unitName syntax.
class _CKBloodGlucoseUnitNamespace {
  const _CKBloodGlucoseUnitNamespace();

  CKBloodGlucoseUnit get millimolesPerLiter => CKBloodGlucoseUnit.millimolesPerLiter;
  CKBloodGlucoseUnit get milligramsPerDeciliter => CKBloodGlucoseUnit.milligramsPerDeciliter;
}

