import 'package:connect_kit/src/models/records/ck_record.dart';

/// Electrocardiogram (ECG/EKG) record
///
/// **Platform Support:**
/// - **iOS**: ✅ Supported (`HKElectrocardiogram`)
/// - **Android**: ❌ NOT SUPPORTED (Health Connect has no ECG type)
///
/// **Note**: ECG records are typically generated by Apple Watch.
/// Manual creation is not supported. This model is for reading existing
/// ECG data from HealthKit.
///
/// **Medical Disclaimer**: ECG data is medical information. Results should
/// be discussed with a healthcare provider. This is not a substitute for
/// professional medical advice.
class CKEcg extends CKRecord {
  /// Medical classification of the heart rhythm
  final CKEcgClassification classification;

  /// Average heart rate during the recording (in BPM)
  final double? averageHeartRate;

  /// User-reported symptoms (if any)
  final List<CKEcgSymptom> symptoms;

  /// Voltage measurements (waveform data)
  /// **Warning**: Each ECG contains ~15,000 measurements
  /// Only populate if you need the full waveform
  final List<CKEcgVoltageMeasurement>? voltageMeasurements;

  /// TODO: add documentation
  const CKEcg({
    super.id,
    required super.startTime,
    required super.endTime,
    super.startZoneOffset,
    super.endZoneOffset,
    super.source,
    required this.classification,
    this.averageHeartRate,
    this.symptoms = const [],
    this.voltageMeasurements,
  });

  /// Duration of the ECG recording
  Duration get recordingDuration => endTime.difference(startTime);

  /// Whether this ECG detected atrial fibrillation
  bool get detectedAFib =>
      classification == CKEcgClassification.atrialFibrillation;

  /// Whether the recording was conclusive
  bool get isConclusive => !classification.name.contains('inconclusive');
}

/// ECG classification (rhythm interpretation)
enum CKEcgClassification {
  /// Not yet classified
  notSet,

  /// Normal sinus rhythm detected
  sinusRhythm,

  /// Atrial fibrillation detected (irregular rhythm)
  atrialFibrillation,

  /// Heart rate too low (<50 bpm) to classify
  inconclusiveLowHeartRate,

  /// Heart rate too high (>120 bpm) to classify
  inconclusiveHighHeartRate,

  /// Other reason preventing classification
  inconclusiveOther,

  /// Generic inconclusive result
  inconclusive,

  /// Unrecognized classification
  unrecognized;
}

/// User-reported symptoms associated with ECG
enum CKEcgSymptom {
  /// No symptoms reported
  none,

  /// Rapid or pounding heartbeat
  rapidPoundingHeartbeat,

  /// Skipped heartbeat sensation
  skippedHeartbeat,

  /// Unusual fatigue
  fatigue,

  /// Shortness of breath
  shortnessOfBreath,

  /// Chest pain or discomfort
  chestPainOrDiscomfort,

  /// Dizziness or lightheadedness
  dizzinessOrLightheadedness;
}

/// Single voltage measurement from ECG waveform
class CKEcgVoltageMeasurement {
  /// Time since start of recording (in seconds)
  final double timeSinceStart;

  /// Voltage in microvolts (µV)
  final double microvolts;

  /// TODO: add documentation
  const CKEcgVoltageMeasurement({
    required this.timeSinceStart,
    required this.microvolts,
  });
}
